### ISSUE TITLE
Does not work with unicode strings

### ISSUE THREAD

**Issue by Aggtaa** [gongzhang/procbridge-nodejs#3]
Sending a unicode string writes an incorrect payload length.

Current implementation incorrectly writes character length of json encoded payload.

Correct approach is to write byte length of json encoded payload.

Example:
Sending `{"method":"console","payload":{"pid":"99d3cc37-3cab-42d8-b44c-25fe92f57014","args":["1"]}}` encodes and writes 90 in the length field.
Sending `{"method":"console","payload":{"pid":"99d3cc37-3cab-42d8-b44c-25fe92f57014","args":["э"]}}` encodes and writes 90 in the length field. **This is incorrect**. The payload is 91 byte long due to the two-byte unicode character `э`.

**Comment by Aggtaa** [comment]
Proposed solution is in https://github.com/gongzhang/procbridge-nodejs/pull/4

**Comment by gongzhang** [comment]
@Aggtaa You are right. Thanks for helping to fix the problem! 🙏

**Comment by gongzhang** [comment]
New version is published: https://www.npmjs.com/package/procbridge/v/1.1.1
